### ISSUE TITLE
How to set the minimum s

### ISSUE THREAD

**Issue by SukantPal** [palantir/react-mosaic#106] opened 2019-03-04 00:52 UTC
I am asking a previously asked, but not answered question: HOW DO YOU SET THE MINIMUM WIDTH/HEIGHT PERCENTAGE VALUE?

It is supposedly 20%. But I want to reduce it.

**Comment by nomcopter** [comment] 2019-03-04 01:22
Duplicate of #22

**Closed by nomcopter** 2019-03-04 01:22 UTC
